name: custom_date_range_picker
description: A Flutter package for both android and iOS which provides a custom date range picker
version: 1.1.0
homepage: https://github.com/mohammadmaree/custom_date_range

environment:
  sdk: ">=2.17.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  easy_localization: ^3.0.7

dev_dependencies:
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter

flutter:

  assets:
    - packages/custom_date_range_picker/src/lang/ar.json
    - packages/custom_date_range_picker/src/lang/en.json
